
    - name: Install and Configure Database  
      apt: name='{{item}}' state:installed
      loop:
       - mysql-server
       - mysql-client

    - name:  Start Database Service
      Service: name=mysql state=started enabled=yes
    
    - namne:  create a new database with name '{{ db_name }}'
      mysql_db:
        name: "{{ db_name }}"
        state: present

    - name: Create database user with name 'bob' and password '12345' with all database privileges
      mysql_user:
        name: "{{db_user}}"
        password: "{{db_password}}"
        priv: '*.*:ALL'
        state: present    