apiVersion: apps/v1
kind: Pod
metadata:
  name: pod1
spec:
   containers:
   - name: busybox1
     image: busybox
     command:
      - /bin/sh
      - -c
      - ls 
      - sleep 3600
       
   - name: busybox2
     image: busybox
     command: ["/bin/sh","-c","echo Hello World", "sleep 3600"]
   - name: busybox3
     image: busybox
     command: ["/bin/sh","-c","echo this is the third container", "sleep 3600"]
---

apiVersion: apps/v1
kind: Pod
metadata:
  name: multi-cont-pod
spec:
   nodeSelector:
    nodeName: nginx
   containers:
     
   - name: main-container
     image: busybox
     command: ["/bin/sh","-c","while true; do echo ‘Hi I am from Main container’ >> /var/log/index.html; sleep 5; done"]
     volumeMounts:
      - mountPath: /var/log
        name: volume
   - name: sidecar 
     image: nginx
     ports:
     - containerPort: 80
     command: ["/bin/sh","-c","echo this is the sidecar container", "sleep 3600"]
     volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: volume
   volumes:
   - name: volume
     emptyDir: {}      
---

apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  serviceAccountName: build-robot
  containers:
  - name: pod1
    image: redis
    ports:
    - containerPort: 80
    volumeMounts:
      - mountPath: /data/redis
        name: volume 
      - mountPath: "/usr/share/nginx/html"
        name: mypd   
      - name: config-volume
        mountPath: /etc/config  
      - name: foo
        mountPath: "/etc/foo"
        readOnly: true  
    envFrom:
    - configMapRef:
        name: keyvalcfgmap 
    - secretRef:
          name: mysecret    
    env:
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              name: envcfgmap 
              key: var1  
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username              

  volumes:
  - emptyDir: {}
    name: volume 
  - name: mypd
    persistentVolumeClaim:
        claimName: task-pv-claim 
  - name: config-volume
    configMap:
        name: cfgvolume 
  - name: foo
    secret:
      secretName: mysecret        
        
---
  
apiVersion: v1
kind: Pod
metadata:
  name: secbusybox
spec:
  serviceAccountName: admin
  securityContext:
    runAsUser: 1000
    runAsGroup: 2000 
  containers:
  - name: pod1
    image:  busybox 
    command: ["sleep 3600"]

    ports:
    - containerPort: 80

    resources:
      limits:
        memory: "200Mi"
        cpu: "1"
      requests:
        memory: "100Mi"
        cpu: "0.5"

    securityContext:
     runAsUser: 8000
     runAsGroup: 9000
     capabilities:
        add: ["NET_ADMIN", "SYS_TIME"]

    readinessProbe:
      httpGet:
        port: 80    
        path: /
      initialDelaySeconds: 20
      periodSeconds: 25  
    livenessProbe:
      httpGet:
        path:  /healthz 
        port:   80 
      initialDelaySeconds: 20
      periodSeconds: 25  

        

