apiVersion: v1
kind: Pod
metadata:
  name: time-check
  namespace: dvl1987
spec:
  volumes:
  - name: a-volume
    emptyDir: {}
  containers:
  - name: time-check
    image: busybox
    volumeMounts:
    - name: a-volume
      mountPath: /opt/time
    command: ["/bin/sh" ,"-c",  "while true; do date; sleep $TIME_FREQ;done > /opt/time/time-check.log " ]
    env:
        # Define the environment variable
        - name: TIME_FREQ
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: time-config
              # Specify the key associated with the value
              key: TIME_FREQ
    