
    - name: Install all required dependencieshon
      apt: name= "{{ item }}" state=installed
      loop:
         - python
         - python-setuptools
         - python-dev
         - build-essential
         - python-pip
         - python-mysqldb
         - git 
