apiVersion: v1
kind: Pod
metadata:
  name: logger
spec:
  containers:
  - name: logger
    image: nginx:alpine
    volumeMounts:
    - name: log-volume
      mountPath: /var/www/nginx
  volumes:
    - name: log-volume
      persistentVolumeClaim:
        claimName: log-claim