---
- name: create a GCP instance
  hosts: localhost
  tasks:
    - name: lauch an instance 
      gcp_compute_instance:
        name: data_base_server
        machine_type: "{{ machine_type }}"
        disks:                  
        - auto_delete: 'true'
          boot: 'true' 
          interface: NVME
          type: SCRATCH
          initialize_params:
            disk_type: local-ssd
            source_image: "{{ source_image }}"

        zone: "{{zone}}"
        project: "{{project}}"
        auth_kind: serviceaccount
        service_account_file: "/tmp/auth.pem"
        service_account_email: "{{ service_account_email }}"
        state: present
      register: gcp_compute_instance  
      with_items: "{{instance_list}}" 

- name: Wait for SSH to come up
  wait_for: host={{ item.public_ip }} port=22 delay=10 timeout=60
  with_items: "{{gcp_compute_instance.results[0].instance_data }}" 

- name: add host to web_servers
  add_host: hostname={{ item.public_ip }} private_ip={{ item.private_ip }} groupname=web_servers    
  with_items: "{{gcp_compute_instance.results[0].instance_data }}"      

- name: add host to database_servers
  add_host: hostname={{ item.public_ip }} private_ip={{ item.private_ip }} groupname=database_servers    
  with_items: "{{gcp_compute_instance.results[1].instance_data }}"  
         