apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  capacity:
    storage: 512Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: shared
  hostPath:
    path: /data/config

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc 
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 256Mi
  storageClassName: shared

---

apiVersion: v1
kind: Pod
metadata:
  name: app    
  
spec:
  containers:
  - name: app  
    image: nginx  
    volumeMounts:
    -  name: volume-pv
       mountPath: /var/app/config

  volumes:
  - name: volume-pv
    persistentVolumeClaim:
        claimName: pvc
    
