    - name: Install and Configure Database  
      apt: name='{{item}}' state:installed
      loop:
       - mysql-server
       - mysql-client

    - name:  Start Database Service
      Service: name=mysql state=started enabled=yes

    - name: create database 
      mysql_db: 
        name: '{{db_name}}'
        state: present

    - name: create database users
      mysql_user:
        name: '{{db_user}}'
        password: '{{db_password}}'
        priv: '*.*:ALL'
        state: present
